modName=DynamicTreesNeapolitan
modId=dtneapolitan
modVersion=1.2.1
group=com.maxhyper.dtneapolitan

mcVersion=1.19.2
forgeVersion=43.2.0
mappingsVersion=2022.11.27

dynamicTreesVersion=1.2.0
dynamicTreesPlusVersion=1.1.4
arlVersion=1.8.2-55
patchouliVersion=1.19.2-77
suggestionProviderFixVersion=1.0.0
ccVersion=1.101.3

curseFileType=release

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false